/*
 * WEth_GeneralTypes.h
 *
 *  Created on: Feb 17, 2022
 *      Author: MBR
 */

#ifndef WETH_INC_WETH_GENERALTYPES_H_
#define WETH_INC_WETH_GENERALTYPES_H_

/*
 * Module Version 1.0.0
 */
#define WETH_GENERAL_TYPES_SW_MAJOR_VERSION                           (1U)
#define WETH_GENERAL_TYPES_SW_MINOR_VERSION                           (0U)
#define WETH_GENERAL_TYPES_SW_PATCH_VERSION                           (0U)

/*
 * AUTOSAR Version 4.7.0
 */
#define WETH_GENERAL_TYPES_AR_RELEASE_MAJOR_VERSION                   (4U)
#define WETH_GENERAL_TYPES_AR_RELEASE_MINOR_VERSION                   (7U)
#define WETH_GENERAL_TYPES_AR_RELEASE_PATCH_VERSION                   (0U)

/*******************************************************************************
 *                         Module Data Types                                     *
 *******************************************************************************/
typedef enum{WETHTRCV_SETCHTXPID_BITRATE ,
	WETHTRCV_SETCHTXPID_BANDWIDTH ,
	WETHTRCV_SETCHTXPID_DCC_CBR ,
	WETHTRCV_SETCHTXPID_TXQSEL,
	WETHTRCV_SETCHTXPID_TXQCFG_AIFSN,
	WETHTRCV_SETCHTXPID_TXQCFG_CWMIN ,
	WETHTRCV_SETCHTXPID_TXQCFG_CWMAX ,
	WETHTRCV_SETCHTXPID_TXQCFG_TXOP ,
	WETHTRCV_SETCHTXPID_RADIO_MODE ,
	WETHTRCV_SETCHTXPID_NTENNA ,
	WETHTRCV_SETCHTXPID_PACKET_INTERVAL ,
	WETHTRCV_SETCHTXPID_DCC_STATE}WEthTrcv_SetChanTxParamIdType;
typedef enum {WETHTRCV_SETRADIOPID_SEL_TRCV_CHCFG = 1,WETHTRCV_SETRADIOPID_SET_CHCFGID, WETHTRCV_SETRADIOPID_OLLINGZONE_INFO }WEthTrcv_SetRadioParamIdType;
typedef enum {WETHTRCV_SETCHRXPID_BITRATE,
	WETHTRCV_SETCHRXPID_BANDWIDTH,
	WETHTRCV_SETCHRXPID_FREQ, WETHTRCV_SETCHRXPID_CSPWRTRESH, WETHTRCV_SETCHRXPID_RADIO_MODE, WETHTRCV_SETCHRXPID_ANTENNA}WEthTrcv_SetChanRxParamIdType;

typedef enum{WETH_BUFWRXPID_RSSI,
	WETH_BUFWRXPID_CHANNEL_ID,
	WETH_BUFWRXPID_FREQ ,
	WETH_BUFWRXPID_TRANSACTION_ID_32,
	WETH_BUFWRXPID_ANTENNA_ID}WEth_BufWRxParamIdType;

typedef enum{WETH_BUFWTXPID_POWER,
	WETH_BUFWTXPID_CHANNEL_ID,
	WETH_BUFWTXPID_QUEUE_ID,
	WETH_BUFWTXPID_TRANSACTION_ID_16,
	WETH_BUFWTXPID_ANTENNA_ID}WEth_BufWTxParamIdType;


/*[SWS_WEthTrcv_10007] -> Wireless channel properties of the receive side*/
typedef enum{
	WETHTRCV_GETCHRXPID_CBR,
	WETHTRCV_GETCHRXPID_CIT
}WEthTrcv_GetChanRxParamIdType;

#endif /* WETH_INC_WETH_GENERALTYPES_H_ */
